defmodule KidsPrep.Notion.Sync do
  @moduledoc false

  alias KidsPrep.Learning
  alias KidsPrep.Learning.Question
  alias KidsPrep.Notion.{Client, Properties}

  def enabled?, do: Client.enabled?()

  def ensure_daily_modules(date \\ Date.utc_today()) do
    if enabled?() do
      for child_slug <- Map.keys(Learning.children()), subject <- Learning.subjects() do
        ensure_daily_module(child_slug, subject, date)
      end
    else
      {:error, :notion_disabled}
    end
  end

  def ensure_daily_module(child_slug, subject, date) do
    questions = Learning.daily_generated_questions(child_slug, subject, date)
    module_key = module_key(child_slug, subject, date)

    with {:ok, []} <- find_module(module_key),
         :ok <- create_question_pages(child_slug, questions, date) do
      create_module_page(child_slug, subject, date, module_key, questions)
    else
      {:ok, [_ | _]} -> {:ok, :already_exists}
      error -> error
    end
  end

  def fetch_daily_questions(child_slug, subject, date \\ Date.utc_today()) do
    module_key = module_key(child_slug, subject, date)

    with true <- enabled?(),
         {:ok, [module_page | _]} <- find_module(module_key),
         {:ok, keys} <- module_question_keys(module_page),
         {:ok, question_pages} <- find_questions(child_slug, subject),
         questions <- pages_to_questions(question_pages, keys),
         true <- questions != [] do
      {:ok, questions}
    else
      _ -> {:error, :not_found}
    end
  end

  def push_result(result) do
    if enabled?() do
      result_key = result_key(result)
      properties = result_properties(result)

      with {:ok, pages} <- find_result(result_key),
           {:ok, _page} <-
             upsert_page(pages, Client.database_id(:results_database_id), properties),
           :ok <- push_weak_skills(result) do
        {:ok, result_key}
      end
    else
      {:error, :notion_disabled}
    end
  end

  defp create_question_pages(child_slug, questions, date) do
    database_id = Client.database_id(:questions_database_id)

    questions
    |> Enum.map(&question_properties(child_slug, &1, date))
    |> Enum.reduce_while(:ok, fn properties, :ok ->
      case Client.create_page(database_id, properties) do
        {:ok, _} -> {:cont, :ok}
        error -> {:halt, error}
      end
    end)
  end

  defp create_module_page(child_slug, subject, date, module_key, questions) do
    child = Learning.child!(child_slug)
    subject_label = Learning.notion_subject_label(subject)
    keys = Enum.map(questions, & &1.id)

    properties = %{
      "Name" => Properties.title("#{child.name} #{subject_label} #{Date.to_iso8601(date)}"),
      "Module Key" => Properties.text(module_key),
      "Child" => Properties.select(child.name),
      "Subject" => Properties.select(subject_label),
      "Module Date" => Properties.date(date),
      "Status" => Properties.status("Not started"),
      "Question Count" => Properties.number(length(questions)),
      "Question Keys JSON" => Properties.text(Jason.encode!(keys)),
      "Generated By" => Properties.select("Scheduler"),
      "Generated At" => Properties.date(DateTime.utc_now())
    }

    Client.create_page(Client.database_id(:daily_modules_database_id), properties)
  end

  defp find_module(module_key) do
    Client.query_database(Client.database_id(:daily_modules_database_id), %{
      filter: %{property: "Module Key", rich_text: %{equals: module_key}},
      page_size: 1
    })
    |> unpack_results()
  end

  defp find_questions(child_slug, subject) do
    child = Learning.child!(child_slug)

    Client.query_database(Client.database_id(:questions_database_id), %{
      filter: %{
        and: [
          %{property: "Subject", select: %{equals: Learning.notion_subject_label(subject)}},
          %{
            or: [
              %{property: "Child", select: %{equals: child.name}},
              %{property: "Child", select: %{equals: "Both"}}
            ]
          },
          %{property: "Active", checkbox: %{equals: true}}
        ]
      },
      page_size: 100
    })
    |> unpack_results()
  end

  defp find_result(result_key) do
    Client.query_database(Client.database_id(:results_database_id), %{
      filter: %{property: "Result Key", rich_text: %{equals: result_key}},
      page_size: 1
    })
    |> unpack_results()
  end

  defp find_weak_skill(weak_skill_key) do
    Client.query_database(Client.database_id(:weak_skills_database_id), %{
      filter: %{property: "Weak Skill Key", rich_text: %{equals: weak_skill_key}},
      page_size: 1
    })
    |> unpack_results()
  end

  defp upsert_page([%{"id" => page_id} | _], _database_id, properties) do
    Client.update_page(page_id, properties)
  end

  defp upsert_page([], database_id, properties) do
    Client.create_page(database_id, properties)
  end

  defp unpack_results({:ok, %{"results" => results}}), do: {:ok, results}
  defp unpack_results(error), do: error

  defp module_question_keys(%{"properties" => properties}) do
    properties
    |> Map.fetch!("Question Keys JSON")
    |> Properties.plain_text()
    |> Jason.decode()
  end

  defp pages_to_questions(pages, keys) do
    pages
    |> Enum.map(&page_to_question/1)
    |> Enum.filter(&(&1.id in keys))
    |> Enum.sort_by(fn question -> Enum.find_index(keys, &(&1 == question.id)) || 999 end)
  end

  defp page_to_question(%{"properties" => properties}) do
    choices =
      ["Choice A", "Choice B", "Choice C", "Choice D"]
      |> Enum.map(&(properties |> Map.fetch!(&1) |> Properties.plain_text()))
      |> Enum.reject(&(&1 == ""))

    %Question{
      id: properties |> Map.fetch!("Question Key") |> Properties.plain_text(),
      subject:
        properties
        |> Map.fetch!("Subject")
        |> Properties.select_name()
        |> Learning.subject_from_label(),
      prompt: properties |> Map.fetch!("Prompt") |> Properties.plain_text(),
      choices: choices,
      answer: properties |> Map.fetch!("Correct Answer") |> Properties.plain_text(),
      explanation: properties |> Map.fetch!("Explanation") |> Properties.plain_text(),
      skill: properties |> Map.fetch!("Skill") |> Properties.plain_text(),
      level: properties |> Map.fetch!("Level") |> Map.get("number")
    }
  end

  defp question_properties(child_slug, question, date) do
    child = Learning.child!(child_slug)
    choices = question.choices ++ List.duplicate("", 4 - length(question.choices))

    %{
      "Name" =>
        Properties.title(
          "#{child.name} #{Learning.subject_label(question.subject)} #{question.skill}"
        ),
      "Question Key" => Properties.text(question.id),
      "Child" => Properties.select(child.name),
      "Subject" => Properties.select(Learning.notion_subject_label(question.subject)),
      "Level" => Properties.number(question.level),
      "Skill" => Properties.text(question.skill),
      "Prompt" => Properties.text(question.prompt),
      "Choice A" => Properties.text(Enum.at(choices, 0)),
      "Choice B" => Properties.text(Enum.at(choices, 1)),
      "Choice C" => Properties.text(Enum.at(choices, 2)),
      "Choice D" => Properties.text(Enum.at(choices, 3)),
      "Correct Answer" => Properties.text(question.answer),
      "Explanation" => Properties.text(question.explanation),
      "Active" => Properties.checkbox(true),
      "Source" => Properties.select("Generated"),
      "Last Used" => Properties.date(date)
    }
  end

  defp result_properties(result) do
    percent = if result.total > 0, do: result.score / result.total * 100, else: 0
    wrong_items = get_in(result.wrong_questions || %{}, ["items"]) || []

    %{
      "Name" =>
        Properties.title(
          "#{result.child_name} #{Learning.subject_label(result.subject)} #{Date.to_iso8601(result.quiz_date)}"
        ),
      "Result Key" => Properties.text(result_key(result)),
      "Child" => Properties.select(result.child_name),
      "Subject" => Properties.select(Learning.notion_subject_label(result.subject)),
      "Module Date" => Properties.date(result.quiz_date),
      "Score" => Properties.number(result.score),
      "Total" => Properties.number(result.total),
      "Percent" => Properties.number(Float.round(percent, 1)),
      "Duration Seconds" => Properties.number(result.duration_seconds || 0),
      "Wrong Count" => Properties.number(length(wrong_items)),
      "Answers JSON" => Properties.text(Jason.encode!(result.answers || %{items: []})),
      "Wrong Questions JSON" =>
        Properties.text(Jason.encode!(result.wrong_questions || %{items: []})),
      "Synced At" => Properties.date(DateTime.utc_now())
    }
  end

  defp push_weak_skills(result) do
    wrong_items = get_in(result.wrong_questions || %{}, ["items"]) || []

    wrong_items
    |> Enum.group_by(&(&1["skill"] || "Unbekannt"))
    |> Enum.reduce_while(:ok, fn {skill, items}, :ok ->
      weak_skill_key = "#{result.child_slug}-#{result.subject}-#{skill}"
      mistake_count = Learning.weak_skill_mistake_count(result.child_slug, result.subject, skill)

      properties = %{
        "Name" =>
          Properties.title(
            "#{result.child_name} #{Learning.subject_label(result.subject)} #{skill}"
          ),
        "Weak Skill Key" => Properties.text(weak_skill_key),
        "Child" => Properties.select(result.child_name),
        "Subject" => Properties.select(Learning.notion_subject_label(result.subject)),
        "Skill" => Properties.text(skill),
        "Mistake Count" => Properties.number(max(mistake_count, length(items))),
        "Priority" => Properties.number(min(max(mistake_count, length(items)) * 2, 10)),
        "Last Seen" => Properties.date(result.quiz_date),
        "Status" => Properties.status("In progress"),
        "Notes" => Properties.text("Automatisch aus falschen Antworten erstellt.")
      }

      case find_weak_skill(weak_skill_key) do
        {:ok, pages} ->
          case upsert_page(pages, Client.database_id(:weak_skills_database_id), properties) do
            {:ok, _page} -> {:cont, :ok}
            error -> {:halt, error}
          end

        error ->
          {:halt, error}
      end
    end)
  end

  defp result_key(result), do: "result-#{result.id}"

  defp module_key(child_slug, subject, date),
    do: "#{Date.to_iso8601(date)}-#{child_slug}-#{subject}"
end
